version: '3'

# Arguments:
#  QT_VERSION=5.12.10
#  QKEYBOARD_SERVICE_PORT=3000

services:

  image_build:
    image: qt-dev:$QT_VERSION
    build:
      args:
        - QT_VERSION=$QT_VERSION
      context: ../
      dockerfile: ./docker/dev/dev.dockerfile
    command: "echo image-build is terminated"
  
  qkeyboard_service:
    image: qkeyboard-service
    build:
      args:
        - QT_VERSION=$QT_VERSION
      context: ../
      dockerfile: ./docker/rel/rel.dockerfile
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    restart: on-failure
    command: "./qt-keyboard-server/AppRun"


