version: '3'

# Arguments:
#  QT_VERSION=5.12.10
#  QKEYBOARD_SERVICE_PORT=3000

# Commands:
# > docker-compose build qt_dev
services:

  qt_dev:
    image: qt-dev:$QT_VERSION
    build:
      args:
        - QT_VERSION=$QT_VERSION
      context: ../
      dockerfile: ./docker/dev/dev.dockerfile
    command: "qt-dev image build completed"
  
  qkeyboard_service:
    image: qkeyboard-service
    build:
      args:
        - QT_VERSION=$QT_VERSION
      context: ../
      dockerfile: ./docker/rel/rel.dockerfile
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    restart: on-failure
    command: "./qt-keyboard-server/AppRun"


